# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cnlint < Formula
  desc ""
  homepage "https://github.com/kurageso/homebrew-cnlint"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurageso/cnlint/releases/download/0.0.8/cnlint_0.0.8_darwin_amd64.tar.gz"
      sha256 "469f8e9478eb4c49eee472ad5d1b0f88cacc015c57851478debac6a1157fe2ed"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurageso/cnlint/releases/download/0.0.8/cnlint_0.0.8_darwin_arm64.tar.gz"
      sha256 "0484e0921286bbc93fa26125d2d48b5fee1cd6f7f575b449fe1cd7405547c0ec"

      def install
        bin.install "program"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kurageso/cnlint/releases/download/0.0.8/cnlint_0.0.8_linux_amd64.tar.gz"
      sha256 "3374bcacbfc7d3ab02ba518e08af4fb72c74ed41de39e09d6e5e8577f095b438"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurageso/cnlint/releases/download/0.0.8/cnlint_0.0.8_linux_arm64.tar.gz"
      sha256 "4fd54766a88085e71d6727ebd0b7286c4c1fa683007aafb28e31a6a23ab390b0"

      def install
        bin.install "program"
      end
    end
  end
end
