# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FileNameAnalyzer < Formula
  desc ""
  homepage "https://github.com/kurageso/homebrew-cnlint"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kurageso/file-name-analyzer/releases/download/0.0.7/file-name-analyzer_0.0.7_darwin_amd64.tar.gz"
      sha256 "7fcc45fc894f768aea87b60fab5b6a30ce44a5d3e12c3f8d7a4e6d50a8b1f6f0"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kurageso/file-name-analyzer/releases/download/0.0.7/file-name-analyzer_0.0.7_darwin_arm64.tar.gz"
      sha256 "5381be353dd7eb73b4618951382d3d88ba4365a04feff5787c6860d9061b9cf6"

      def install
        bin.install "program"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kurageso/file-name-analyzer/releases/download/0.0.7/file-name-analyzer_0.0.7_linux_arm64.tar.gz"
      sha256 "adf8e2f9cee58a69218d3121b6c807e1741065bd0aa5c8861d313c15f80df5ce"

      def install
        bin.install "program"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kurageso/file-name-analyzer/releases/download/0.0.7/file-name-analyzer_0.0.7_linux_amd64.tar.gz"
      sha256 "1ffc276426ce55269d4e55483d73f55fdacd1b29c8d53987fe520a536bf9b97b"

      def install
        bin.install "program"
      end
    end
  end
end
